Prepare first release
qbicsoftware/sample-tracking-helper-lib pull request #2
Opened 2020-03-10 12:13 UTC by sven1103

2020-03-10 12:17 UTC, sven1103 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor tracking helper library](https://trello.com/c/oQ3OojQm/42-refactor-tracking-helper-library)

2020-03-10 12:59 UTC, Zethson commented on test/LICENSE
> +Copyright (c) 2019 QBiC
2020? :)

2020-03-12 14:39 UTC, wow-such-code requested changes
change year in test/.gitignore

2020-03-12 14:39 UTC, wow-such-code commented on test/LICENSE
> +Copyright (c) 2019 QBiC
wrong year!

2020-03-12 15:17 UTC, wow-such-code approved these changes

2020-03-12 15:31 UTC, merged